feat: add default postional arg (#15)
In previous version, argc do not allow positional arguments if subcommand has no @arg tag.

Create a demo.sh
```sh
cmd() {
  echo ${argc__args[@]}
  :;
}

eval "$(argc -e $0 "$@")"
```

Run it

```

$ bash demo.sh cmd foo
error: Found argument 'a' which wasn't expected, or isn't valid in this context

USAGE:
    demo cmd

For more information try --help

```

After this pr merged, A default postional arg is implicitly added.
Argc can collect postional args and put it into `$argc__args` variable.

```
$ bash demo.sh cmd foo bar
foo bar

$ argc -e demo.sh cmd foo bar
argc__args=( foo bar )
cmd
```